### ISSUE TITLE
Subscribe to Nova notifications

### ISSUE THREAD

**Issue by julianpistorius** [exosphere-project/exosphere#26]
... instead of polling.

- <https://wiki.openstack.org/wiki/NotificationSystem>
- <https://blueprints.launchpad.net/nova/+spec/notification-system>
- <https://docs.openstack.org/nova/latest/reference/rpc.html>
- <https://wiki.openstack.org/wiki/Oslo/Messaging>
  - Specifically: <https://wiki.openstack.org/wiki/Oslo/Messaging#oslo.notify>
- <https://ilearnstack.com/2013/04/24/messaging-in-openstack-using-rabbitmq/>
- <https://prosuncsedu.wordpress.com/2013/11/09/intercept-rabbitmq-messages-in-openstack-nova/>

Q: Can we subscribe to AMQP from the browser and be notified using WebSockets?
A: Apparently yes. With caveats. It seems an admin either has to configure RabbitMQ to allow direct publishing to WebSockets:
- <https://alexfranchuk.com/blog/amqp-using-websockets/>
- <https://www.rabbitmq.com/web-stomp.html>
- <https://stackoverflow.com/questions/34179845/amqp-over-websocket-with-rabbitmq>
- <https://sjmf.in/wp/?p=86>

... Or we need a 'face hugger' intermediary:
- <https://www.youtube.com/watch?v=lOyG6ZMq738>
- <https://stackoverflow.com/questions/25635532/easiest-way-to-push-rabbitmq-events-to-browser-using-websockets-in-python>
- <https://www.npmjs.com/package/socket.io-amqp>

**Comment by c-mart** [comment]
@julianpistorius you explained to me that this wasn't a good use of effort now due to above caveats. I suggest closing this issue if the effort/complexity is too great for the foreseeable benefit.

**Comment by julianpistorius** [comment]
Yep - close it.
