### ISSUE TITLE
Use boot script to notify when instance finished launching

### ISSUE THREAD

**Issue by julianpistorius** [exosphere-project/exosphere#27]
Maybe can also notify when external IP address is received.

Can publish to IPFS PubSub to avoid needing a backend.

**Comment by c-mart** [comment]
At this stage, I don't think any action is really necessary because polling works?

> Maybe can also notify when external IP address is received.

We know this as soon as the floating IP associate call returns, right? In my experience the instance is ready to accept (at least SSH) connections basically as soon as the floating IP is associated.

**Comment by julianpistorius** [comment]
> At this stage, I don't think any action is really necessary because polling works?

Yup.

**Comment by c-mart** [comment]
OK, closing.
