### ISSUE TITLE
Evaluate API design

### ISSUE THREAD

**Issue by julianpistorius** [exosphere-project/exosphere#40]
Useful info: http://package.elm-lang.org/help/design-guidelines

Then maybe get a code review from somebody on the Elm Slack?

**Comment by c-mart** [comment]
Issue description unclear; evaluate design of which API?

**Comment by julianpistorius** [comment]
Well this is embarrassing. I thought _you_ created the initial card on the project, and I just converted it into an issue and added the link. 😆 I blame lack of sleep.

I _think_ this referred to the design of the API of the 'business logic' part of the app - the modules plus the functions and types which they expose - excluding the overtly 'UI' parts.

Happy to close, or revisit much later.

**Comment by c-mart** [comment]
Ya. I think issues should be well-defined and actionable, this one doesn't make the cut.
